# Generated by Django 3.1.6 on 2021-03-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
